.TH EXIFDUMP 1
.\"
.\" Copyright (c) 2001, 2002, Eric M. Johnston <emj@postal.net>
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"      This product includes software developed by Eric M. Johnston.
.\" 4. Neither the name of the author nor the names of any co-contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
.\" IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
.\" OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
.\" IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
.\" INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
.\" NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
.\" THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.\" $Id: exiftags.1,v 1.9 2002/07/15 00:00:12 ejohnst Exp $
.\"
.SH NAME
.B exiftags
\- output the properties contained in a JPEG Exif section
.SH SYNOPSIS
.B exiftags
[
.B \-acdiquv
] [
.I file ...
]
.SH DESCRIPTION
The
.B exiftags
utility parses
.I file
or, by default, its standard input, looking for a JPEG APP1 section
containing Exif (Exchangeable Image File) data.  The properties contained in
these data are then printed to the standard output.

Digitial cameras typically add Exif data to the image files they produce,
containing information about the camera and digitized image.  The options
described below may be used to control output verbosity and section
formatting.
.SH OPTIONS
.IP -a
Output camera-specific, image-specific, and verbose properties contained in
the file.
.IP -c
Output camera-specific properties contained in the file.
.IP -d
Output Exif parse debug information.
.IP -i
Output image-specific properties contained in the file.
.IP -q
Suppress output of a property section header.
.IP -u
Output unknown or unsupported properties contained in the file.
.IP -v
Output verbose properties contained in the file.
.SH MAKER NOTES
Some camera manufacturers include a "maker note" section with additional
information about the camera or image not part of the Exif standard.
The format of these maker notes varies wildly and manufacturers are not
forthcoming with implementation details.  Therefore,
.B exiftags
maker note support is the result of experimentation and reverse engineering
(see below for credits) and incomplete.
.B exiftags
is known to have at least partial support for the following cameras'
maker notes:
.IP "" 4
Canon/Canon DIGITAL IXUS
.br
Canon/Canon EOS D30
.br
Canon/Canon EOS D60
.br
Canon/Canon PowerShot S100
.br
Canon/Canon PowerShot S110
.br
Canon/Canon PowerShot S20
.br
Canon/Canon PowerShot S30
.br
Canon/Canon PowerShot S40
.br
FUJIFILM/FinePix2600Zoom
.br
FUJIFILM/FinePix40i
.br
NIKON/E880
.br
NIKON/E950
.br
NIKON/E990
.br
NIKON/E995
.br
OLYMPUS OPTICAL CO.,LTD/C2040Z
.br
OLYMPUS OPTICAL CO.,LTD/C3030Z
.br
OLYMPUS OPTICAL CO.,LTD/C960Z,D460Z
.PP
If you wish support for additional
manufacturers or cameras, please send any information you have
about the data format or, better yet, patches, and a sample image file
to the author.  (Though he makes no promises.)
.SH DIAGNOSTICS
The
.B exiftags
utility exit 0 on success, and >0 if an error occurs.
.SH STANDARDS
The
.B exiftags
utility was developed using the June 1998 Exif standard, version 2.1
(http://www.pima.net/standards/it10/PIMA15740/Exif_2-1.PDF) and the June 1992
TIFF specification, revision 6.0
(http://partners.adobe.com/asn/developer/pdfs/tn/TIFF6.pdf).
.SH BUGS
Not all Exif 2.1 properties are supported, due either to the author's laziness
or incomplete information.  Maker note support is spotty due to lack of
information.
.SH AUTHOR
The
.B exiftags
utility and this man page were written by Eric M. Johnston <emj@postal.net>.
Portions of the utility were developed while referencing the public domain
Jhead utility, version 1.2, by Matthias Wandel <mwandel@rim.net>.
Maker note support is largely the result of TsuruZoh Tachibanaya's
compendium (http://www.ba.wakwak.com/~tsuruzoh/Computer/Digicams/exif-e.html)
and its contributers.
.PP
Special thanks to the following folks for submitting sample camera files:
Marcy Brown, Frank Fortunato, Kaye Kirsch, Jamie Mayberry, Michael Shostak,
and Phillip Wherry.
